import { Exercise } from '../../../domain/entities/Exercise'
import type { ExerciseProps } from '../../../domain/entities/Exercise'

const EXERCISES_DATA: ExerciseProps[] = [
  // ===== PECHO =====
  {
    id: 'chest-barbell-bench-press',
    name: 'Barbell Bench Press',
    nameEs: 'Press de Banca con Barra',
    muscleGroups: { primary: ['chest'], secondary: ['shoulders', 'triceps'] },
    equipment: ['barbell', 'bench'],
    movementPattern: 'push-horizontal',
    difficulty: 'intermediate',
    instructions: ['Acuéstate en el banco con los pies en el suelo', 'Agarra la barra a la altura de los hombros', 'Baja la barra controlando hasta el pecho', 'Empuja explosivamente hasta extender los codos'],
    commonMistakes: ['Arquear excesivamente la espalda', 'Rebotar la barra en el pecho', 'Codos muy abiertos (90°)'],
    tips: ['Retrae y deprime las escápulas', 'Mantén las muñecas rectas', 'Aprieta la barra con fuerza'],
    variants: ['chest-incline-bench-press', 'chest-close-grip-bench', 'chest-dumbbell-bench-press'],
  },
  {
    id: 'chest-incline-bench-press',
    name: 'Incline Barbell Bench Press',
    nameEs: 'Press Inclinado con Barra',
    muscleGroups: { primary: ['chest'], secondary: ['shoulders', 'triceps'] },
    equipment: ['barbell', 'bench'],
    movementPattern: 'push-horizontal',
    difficulty: 'intermediate',
    instructions: ['Ajusta el banco a 30-45°', 'Agarra la barra un poco más estrecha que en el press plano', 'Baja la barra hacia el pecho superior', 'Empuja hacia arriba y ligeramente atrás'],
    commonMistakes: ['Ángulo demasiado alto (>45°) que activa más deltoides', 'No controlar la bajada'],
    tips: ['30° activa más pecho que 45°', 'El toque es en el pecho superior, no en la garganta'],
    variants: ['chest-barbell-bench-press', 'chest-incline-dumbbell-press'],
  },
  {
    id: 'chest-decline-bench-press',
    name: 'Decline Bench Press',
    nameEs: 'Press Declinado',
    muscleGroups: { primary: ['chest'], secondary: ['triceps'] },
    equipment: ['barbell', 'bench'],
    movementPattern: 'push-horizontal',
    difficulty: 'intermediate',
    instructions: ['Asegura los pies en el banco declinado', 'Agarra la barra a la anchura de hombros', 'Baja al pecho inferior controladamente', 'Empuja hacia arriba'],
    commonMistakes: ['Bajar demasiado rápido', 'No asegurar bien los pies'],
    tips: ['Activa especialmente el pecho inferior', 'Menor estrés en los hombros que el press plano'],
    variants: ['chest-barbell-bench-press'],
  },
  {
    id: 'chest-dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    nameEs: 'Press de Banca con Mancuernas',
    muscleGroups: { primary: ['chest'], secondary: ['shoulders', 'triceps'] },
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'push-horizontal',
    difficulty: 'beginner',
    instructions: ['Siéntate en el banco con mancuernas sobre muslos', 'Acuéstate llevando las mancuernas a los lados del pecho', 'Empuja hacia arriba girando ligeramente las manos', 'Baja controladamente hasta estirar el pecho'],
    commonMistakes: ['Dejar que los codos caigan demasiado', 'No mantener tensión en la parte inferior'],
    tips: ['Mayor rango de movimiento que con barra', 'Trabaja cada brazo independientemente'],
    variants: ['chest-barbell-bench-press', 'chest-incline-dumbbell-press'],
  },
  {
    id: 'chest-incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    nameEs: 'Press Inclinado con Mancuernas',
    muscleGroups: { primary: ['chest'], secondary: ['shoulders', 'triceps'] },
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'push-horizontal',
    difficulty: 'beginner',
    instructions: ['Banco a 30-45°', 'Mancuernas a los lados del pecho superior', 'Empuja hacia arriba', 'Baja controlando'],
    commonMistakes: ['Ángulo demasiado alto'],
    tips: ['Excelente para el pecho superior', 'Mantén los codos a 45° del cuerpo'],
    variants: ['chest-incline-bench-press', 'chest-dumbbell-bench-press'],
  },
  {
    id: 'chest-dips',
    name: 'Chest Dips',
    nameEs: 'Fondos de Pecho',
    muscleGroups: { primary: ['chest'], secondary: ['triceps', 'shoulders'] },
    equipment: ['bodyweight'],
    movementPattern: 'push-horizontal',
    difficulty: 'intermediate',
    instructions: ['Agarra las barras paralelas', 'Inclínate hacia adelante ~30°', 'Baja hasta que los codos estén a 90°', 'Empuja hacia arriba manteniendo la inclinación'],
    commonMistakes: ['No inclinarse hacia adelante (activa más tríceps)', 'Bajar demasiado y lesionar los hombros'],
    tips: ['La inclinación hacia adelante es clave para activar el pecho', 'Añade peso con cinturón cuando sea necesario'],
    variants: ['chest-barbell-bench-press'],
  },
  {
    id: 'chest-cable-crossover',
    name: 'Cable Crossover',
    nameEs: 'Cruce de Cables',
    muscleGroups: { primary: ['chest'], secondary: [] },
    equipment: ['cable'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Coloca los cables a la altura de los hombros', 'Inclínate ligeramente hacia adelante', 'Cruza los cables frente al pecho', 'Controla el regreso'],
    commonMistakes: ['Usar demasiado peso y perder la contracción', 'No mantener tensión al cruzar'],
    tips: ['Excelente ejercicio de aislamiento para el pecho', 'Enfócate en la contracción al cruzar'],
    variants: ['chest-pec-deck', 'chest-cable-fly'],
  },
  {
    id: 'chest-pec-deck',
    name: 'Pec Deck Machine',
    nameEs: 'Apertura en Máquina (Pec Deck)',
    muscleGroups: { primary: ['chest'], secondary: [] },
    equipment: ['machine'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Ajusta el asiento para que los codos queden a la altura de los hombros', 'Cierra los brazos hacia el centro', 'Aprieta el pecho al final', 'Regresa controladamente'],
    commonMistakes: ['Abrir demasiado los brazos en la fase excéntrica'],
    tips: ['Ideal para el final del entrenamiento', 'Mantén la contracción 1 segundo en el punto de máxima tensión'],
    variants: ['chest-cable-crossover'],
  },
  {
    id: 'chest-cable-fly',
    name: 'Cable Fly',
    nameEs: 'Aperturas con Cable',
    muscleGroups: { primary: ['chest'], secondary: [] },
    equipment: ['cable'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Cables en posición baja o alta según el ángulo deseado', 'Mantén los codos ligeramente flexionados', 'Lleva los cables hacia el centro', 'Regresa controladamente'],
    commonMistakes: ['Flexionar demasiado los codos (convierte en press)'],
    tips: ['Cables bajos activan el pecho superior, cables altos el inferior'],
    variants: ['chest-cable-crossover', 'chest-dumbbell-fly'],
  },
  {
    id: 'chest-dumbbell-fly',
    name: 'Dumbbell Fly',
    nameEs: 'Apertura con Mancuernas',
    muscleGroups: { primary: ['chest'], secondary: [] },
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Acuéstate en el banco con mancuernas sobre el pecho', 'Baja los brazos en arco manteniendo codos ligeramente doblados', 'Siente el estiramiento en el pecho', 'Sube en el mismo arco'],
    commonMistakes: ['Bajar demasiado y lesionar el hombro', 'Doblar demasiado los codos'],
    tips: ['Prioriza el control sobre el peso', 'El estiramiento es el objetivo principal'],
    variants: ['chest-cable-fly'],
  },
  {
    id: 'chest-push-up',
    name: 'Push-Up',
    nameEs: 'Flexiones de Pecho',
    muscleGroups: { primary: ['chest'], secondary: ['triceps', 'shoulders', 'core'] },
    equipment: ['bodyweight'],
    movementPattern: 'push-horizontal',
    difficulty: 'beginner',
    instructions: ['Coloca las manos a la anchura de hombros', 'Cuerpo recto de cabeza a talones', 'Baja hasta casi tocar el pecho en el suelo', 'Empuja hasta extender los codos'],
    commonMistakes: ['Cadera hacia arriba o abajo', 'Codos muy abiertos'],
    tips: ['Excelente para calentamiento o como ejercicio accesorio', 'Añade dificultad con pies elevados'],
    variants: ['chest-dips', 'chest-barbell-bench-press'],
  },
  // ===== ESPALDA =====
  {
    id: 'back-deadlift',
    name: 'Deadlift',
    nameEs: 'Peso Muerto',
    muscleGroups: { primary: ['back', 'lats'], secondary: ['hamstrings', 'glutes', 'traps', 'forearms'] },
    equipment: ['barbell'],
    movementPattern: 'hinge',
    difficulty: 'advanced',
    instructions: ['Barra sobre los medios pies', 'Agarre a la anchura de caderas', 'Espalda neutra, pecho hacia adelante', 'Empuja el suelo y extiende caderas y rodillas simultáneamente'],
    commonMistakes: ['Redondear la espalda baja', 'La barra se aleja del cuerpo', 'Arrancar con los brazos'],
    tips: ['La barra debe rozar las piernas todo el camino', 'Piensa en "empujar el suelo" en lugar de "tirar de la barra"'],
    variants: ['back-romanian-deadlift', 'back-sumo-deadlift'],
  },
  {
    id: 'back-pull-up',
    name: 'Pull-Up',
    nameEs: 'Dominadas',
    muscleGroups: { primary: ['lats', 'back'], secondary: ['biceps', 'forearms'] },
    equipment: ['pull-up-bar'],
    movementPattern: 'pull-vertical',
    difficulty: 'intermediate',
    instructions: ['Agarre prono, anchura de hombros o ligeramente más amplio', 'Cuelga completamente con los brazos extendidos', 'Tira de los codos hacia abajo y atrás', 'Sube hasta que la barbilla supere la barra'],
    commonMistakes: ['No completar el rango de movimiento', 'Usar impulso con las piernas (kipping)'],
    tips: ['Retrae las escápulas antes de subir', 'Imagina que aprietas limones en las axilas'],
    variants: ['back-lat-pulldown', 'back-chin-up'],
  },
  {
    id: 'back-chin-up',
    name: 'Chin-Up',
    nameEs: 'Dominadas Supinas',
    muscleGroups: { primary: ['lats', 'biceps'], secondary: ['back'] },
    equipment: ['pull-up-bar'],
    movementPattern: 'pull-vertical',
    difficulty: 'intermediate',
    instructions: ['Agarre supino a la anchura de hombros', 'Baja completamente', 'Sube tirando de los codos hacia la cadera', 'Sube hasta que la barbilla supere la barra'],
    commonMistakes: ['No llegar abajo completamente'],
    tips: ['Mayor activación de bíceps que las dominadas prenas', 'Más fácil para principiantes'],
    variants: ['back-pull-up', 'back-lat-pulldown'],
  },
  {
    id: 'back-barbell-row',
    name: 'Barbell Row',
    nameEs: 'Remo con Barra',
    muscleGroups: { primary: ['back', 'lats'], secondary: ['biceps', 'traps', 'forearms'] },
    equipment: ['barbell'],
    movementPattern: 'pull-horizontal',
    difficulty: 'intermediate',
    instructions: ['Inclínate a 45° con espalda recta', 'Agarra la barra a la anchura de hombros', 'Tira hacia el abdomen', 'Baja controladamente'],
    commonMistakes: ['Redondear la espalda', 'Usar impulso con el cuerpo', 'Tirar demasiado arriba (hacia el pecho)'],
    tips: ['Los codos deben ir hacia atrás, no hacia los lados', 'Mantén la inclinación constante'],
    variants: ['back-dumbbell-row', 'back-cable-row'],
  },
  {
    id: 'back-dumbbell-row',
    name: 'Dumbbell Row',
    nameEs: 'Remo con Mancuerna',
    muscleGroups: { primary: ['lats', 'back'], secondary: ['biceps', 'forearms'] },
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'pull-horizontal',
    difficulty: 'beginner',
    instructions: ['Apoya la rodilla y mano en el banco', 'Espalda paralela al suelo', 'Tira la mancuerna hacia la cadera', 'Baja hasta el estiramiento completo'],
    commonMistakes: ['Rotar el torso', 'No bajar completamente'],
    tips: ['Enfócate en mover el codo, no la mano', 'Mantén la cadera quieta'],
    variants: ['back-barbell-row', 'back-lat-pulldown'],
  },
  {
    id: 'back-lat-pulldown',
    name: 'Lat Pulldown',
    nameEs: 'Jalón al Pecho',
    muscleGroups: { primary: ['lats'], secondary: ['biceps', 'back'] },
    equipment: ['cable', 'machine'],
    movementPattern: 'pull-vertical',
    difficulty: 'beginner',
    instructions: ['Siéntate con muslos bajo los rodillos', 'Agarra la barra a la anchura de hombros o más', 'Tira hacia el pecho llevando los codos abajo', 'Controla el regreso'],
    commonMistakes: ['Tirar detrás del cuello (lesiona cervicales)', 'Inclinarse demasiado hacia atrás'],
    tips: ['Imagina que tratas de meter los codos en los bolsillos traseros', 'Ligera inclinación hacia atrás es correcta'],
    variants: ['back-pull-up', 'back-chin-up'],
  },
  {
    id: 'back-cable-row',
    name: 'Cable Row',
    nameEs: 'Remo en Polea',
    muscleGroups: { primary: ['back', 'lats'], secondary: ['biceps', 'traps'] },
    equipment: ['cable'],
    movementPattern: 'pull-horizontal',
    difficulty: 'beginner',
    instructions: ['Siéntate frente al cable con pies en el soporte', 'Agarra el accesorio de remo', 'Tira hacia el abdomen', 'Controla el regreso con tensión'],
    commonMistakes: ['Redondear la espalda al final', 'No retraer las escápulas'],
    tips: ['Al llegar atrás, aprieta las escápulas juntas', 'Mantén el torso erguido'],
    variants: ['back-barbell-row', 'back-dumbbell-row'],
  },
  {
    id: 'back-t-bar-row',
    name: 'T-Bar Row',
    nameEs: 'Remo en T',
    muscleGroups: { primary: ['back', 'lats'], secondary: ['biceps', 'traps'] },
    equipment: ['barbell'],
    movementPattern: 'pull-horizontal',
    difficulty: 'intermediate',
    instructions: ['Mete la barra en el soporte de T', 'Inclínate con espalda recta', 'Agarra las asas', 'Tira hacia el pecho'],
    commonMistakes: ['Redondear la espalda'],
    tips: ['Excelente para masa de espalda media', 'Permite mover más peso que el remo con mancuerna'],
    variants: ['back-barbell-row'],
  },
  {
    id: 'back-face-pull',
    name: 'Face Pull',
    nameEs: 'Face Pull',
    muscleGroups: { primary: ['traps', 'shoulders'], secondary: ['back'] },
    equipment: ['cable'],
    movementPattern: 'pull-horizontal',
    difficulty: 'beginner',
    instructions: ['Cable a altura de cara', 'Agarra la cuerda con prono', 'Tira hacia la cara separando las manos', 'Regresa controladamente'],
    commonMistakes: ['Cable demasiado bajo', 'No separar las manos al final'],
    tips: ['Excelente para la salud del hombro', 'Útil como ejercicio correctivo y de calentamiento'],
    variants: ['back-cable-row'],
  },
  {
    id: 'back-romanian-deadlift',
    name: 'Romanian Deadlift',
    nameEs: 'Peso Muerto Rumano',
    muscleGroups: { primary: ['hamstrings', 'glutes'], secondary: ['back', 'forearms'] },
    equipment: ['barbell'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    instructions: ['Empieza de pie con barra en las manos', 'Mantén las piernas ligeramente flexionadas', 'Baja la barra rozando las piernas', 'Siente el estiramiento en los isquios y sube'],
    commonMistakes: ['Doblar demasiado las rodillas (se convierte en sentadilla)', 'Redondear la espalda'],
    tips: ['Las caderas van hacia atrás, no hacia abajo', 'El movimiento es una bisagra de cadera'],
    variants: ['back-deadlift', 'back-sumo-deadlift'],
  },
  {
    id: 'back-sumo-deadlift',
    name: 'Sumo Deadlift',
    nameEs: 'Peso Muerto Sumo',
    muscleGroups: { primary: ['glutes', 'hamstrings', 'back'], secondary: ['quadriceps', 'traps'] },
    equipment: ['barbell'],
    movementPattern: 'hinge',
    difficulty: 'advanced',
    instructions: ['Stance ancho, puntas hacia afuera', 'Agarre interior, más estrecho que en convencional', 'Caderas bajas, espalda recta', 'Empuja el suelo y abre las rodillas'],
    commonMistakes: ['Caderas suben antes que el torso', 'Rodillas colapsando hacia adentro'],
    tips: ['Mayor activación de glúteos y cuádriceps que el convencional', 'Ideal para personas con torso largo'],
    variants: ['back-deadlift'],
  },
  {
    id: 'back-hyperextension',
    name: 'Back Extension',
    nameEs: 'Extensión de Espalda',
    muscleGroups: { primary: ['back'], secondary: ['glutes', 'hamstrings'] },
    equipment: ['machine'],
    movementPattern: 'hinge',
    difficulty: 'beginner',
    instructions: ['Colócate en el banco de extensiones con caderas en el borde', 'Baja el torso hasta 90°', 'Sube hasta que el cuerpo esté horizontal', 'Aprieta los glúteos arriba'],
    commonMistakes: ['Hiperextenderse más allá de horizontal', 'Usar el cuello para subir'],
    tips: ['Añade peso con plato al pecho para más intensidad'],
    variants: ['back-romanian-deadlift'],
  },
  // ===== HOMBROS =====
  {
    id: 'shoulders-overhead-press',
    name: 'Overhead Press',
    nameEs: 'Press Militar',
    muscleGroups: { primary: ['shoulders'], secondary: ['triceps', 'traps'] },
    equipment: ['barbell'],
    movementPattern: 'push-vertical',
    difficulty: 'intermediate',
    instructions: ['Barra en la parte frontal de los hombros', 'Pies a la anchura de caderas', 'Empuja hacia arriba en línea vertical', 'Baja la barra controladamente'],
    commonMistakes: ['Arquear la espalda baja', 'Empujar hacia adelante en lugar de vertical'],
    tips: ['Al pasar la frente, mete la cabeza "por la ventana"', 'Glúteos y abdomen activados'],
    variants: ['shoulders-dumbbell-shoulder-press', 'shoulders-arnold-press'],
  },
  {
    id: 'shoulders-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    nameEs: 'Press de Hombros con Mancuernas',
    muscleGroups: { primary: ['shoulders'], secondary: ['triceps'] },
    equipment: ['dumbbell'],
    movementPattern: 'push-vertical',
    difficulty: 'beginner',
    instructions: ['Sentado o de pie con mancuernas a la altura de los hombros', 'Empuja hacia arriba hasta casi extender los codos', 'Baja controladamente'],
    commonMistakes: ['Extender completamente los codos (bloquear)'],
    tips: ['Mayor rango de movimiento y balance que con barra'],
    variants: ['shoulders-overhead-press', 'shoulders-arnold-press'],
  },
  {
    id: 'shoulders-arnold-press',
    name: 'Arnold Press',
    nameEs: 'Press Arnold',
    muscleGroups: { primary: ['shoulders'], secondary: ['triceps'] },
    equipment: ['dumbbell'],
    movementPattern: 'push-vertical',
    difficulty: 'intermediate',
    instructions: ['Empieza con mancuernas frente a ti, palmas mirando hacia ti', 'Gira las palmas hacia afuera al subir', 'Sube hasta casi extender', 'Baja revirtiendo la rotación'],
    commonMistakes: ['Girar muy rápido'],
    tips: ['Trabaja más los deltoides anteriores', 'Excelente para agregar variedad'],
    variants: ['shoulders-dumbbell-shoulder-press'],
  },
  {
    id: 'shoulders-lateral-raise',
    name: 'Lateral Raise',
    nameEs: 'Elevaciones Laterales',
    muscleGroups: { primary: ['shoulders'], secondary: [] },
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Mancuernas a los lados', 'Sube los brazos hasta la altura de los hombros', 'Pulgares ligeramente hacia abajo al final', 'Baja controladamente'],
    commonMistakes: ['Usar impulso del cuerpo', 'Subir demasiado alto (trapecios toman el trabajo)'],
    tips: ['El peso máximo es al nivel de los hombros', 'Eje del movimiento en el hombro, no el codo'],
    variants: ['shoulders-cable-lateral-raise'],
  },
  {
    id: 'shoulders-cable-lateral-raise',
    name: 'Cable Lateral Raise',
    nameEs: 'Elevación Lateral en Cable',
    muscleGroups: { primary: ['shoulders'], secondary: [] },
    equipment: ['cable'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Cable en posición baja', 'Levanta el brazo lateral hasta la altura del hombro', 'Regresa controladamente'],
    commonMistakes: ['Permitir que el cable tire el brazo hacia abajo rápido'],
    tips: ['Tensión constante en todo el rango', 'Ideal para unilateral'],
    variants: ['shoulders-lateral-raise'],
  },
  {
    id: 'shoulders-rear-delt-fly',
    name: 'Rear Delt Fly',
    nameEs: 'Pájaro / Vuelo para Deltoides Posterior',
    muscleGroups: { primary: ['shoulders', 'traps'], secondary: ['back'] },
    equipment: ['dumbbell'],
    movementPattern: 'pull-horizontal',
    difficulty: 'beginner',
    instructions: ['Inclinado hacia adelante o en banco inclinado', 'Mancuernas colgando', 'Abre los brazos hacia los lados', 'Aprieta la espalda alta al final'],
    commonMistakes: ['Usar impulso', 'Peso excesivo'],
    tips: ['Mantén la cabeza neutral', 'Codos ligeramente flexionados'],
    variants: ['back-face-pull'],
  },
  {
    id: 'shoulders-front-raise',
    name: 'Front Raise',
    nameEs: 'Elevaciones Frontales',
    muscleGroups: { primary: ['shoulders'], secondary: [] },
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Mancuernas frente a los muslos', 'Levanta un brazo hacia adelante hasta la altura de los hombros', 'Baja controladamente', 'Alterna o simultáneo'],
    commonMistakes: ['Usar impulso con el cuerpo'],
    tips: ['Activa el deltoides anterior', 'Generalmente suficientemente activado con press'],
    variants: ['shoulders-overhead-press'],
  },
  // ===== BÍCEPS =====
  {
    id: 'biceps-barbell-curl',
    name: 'Barbell Curl',
    nameEs: 'Curl con Barra',
    muscleGroups: { primary: ['biceps'], secondary: ['forearms'] },
    equipment: ['barbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Agarre supino a la anchura de caderas', 'Codos pegados al cuerpo', 'Flexiona hasta contraer completamente', 'Baja controladamente'],
    commonMistakes: ['Mover los codos hacia adelante', 'Usar impulso del cuerpo'],
    tips: ['Los codos son el eje, no deben moverse', 'Supina la muñeca al subir'],
    variants: ['biceps-ez-bar-curl', 'biceps-dumbbell-curl'],
  },
  {
    id: 'biceps-ez-bar-curl',
    name: 'EZ-Bar Curl',
    nameEs: 'Curl con Barra EZ',
    muscleGroups: { primary: ['biceps'], secondary: ['forearms', 'traps'] },
    equipment: ['ez-bar'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Agarra la barra EZ en el agarre más interior', 'Codos fijos al cuerpo', 'Flexiona controladamente', 'Baja hasta extensión completa'],
    commonMistakes: ['Mover los codos'],
    tips: ['Menos estrés en las muñecas que la barra recta', 'Muy popular y efectivo'],
    variants: ['biceps-barbell-curl', 'biceps-dumbbell-curl'],
  },
  {
    id: 'biceps-dumbbell-curl',
    name: 'Dumbbell Curl',
    nameEs: 'Curl con Mancuernas',
    muscleGroups: { primary: ['biceps'], secondary: ['forearms'] },
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Mancuernas a los lados, palmas hacia adelante', 'Codos fijos', 'Flexiona alternando o simultáneo', 'Supina al subir'],
    commonMistakes: ['No suprnar la muñeca'],
    tips: ['La supinación añade contracción extra al bíceps'],
    variants: ['biceps-barbell-curl', 'biceps-hammer-curl'],
  },
  {
    id: 'biceps-hammer-curl',
    name: 'Hammer Curl',
    nameEs: 'Curl Martillo',
    muscleGroups: { primary: ['biceps'], secondary: ['forearms', 'traps'] },
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Mancuernas con agarre neutro (pulgares arriba)', 'Codos fijos al cuerpo', 'Flexiona hasta la contracción', 'Baja controladamente'],
    commonMistakes: ['Mover los codos'],
    tips: ['Trabaja más el braquial y braquiorradial que el bíceps', 'Añade grosor al brazo'],
    variants: ['biceps-dumbbell-curl'],
  },
  {
    id: 'biceps-preacher-curl',
    name: 'Preacher Curl',
    nameEs: 'Curl en Predicador',
    muscleGroups: { primary: ['biceps'], secondary: ['forearms'] },
    equipment: ['barbell', 'ez-bar'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Apoya los tríceps en el banco predicador', 'Agarre supino', 'Flexiona completamente', 'Baja muy lento para máximo estiramiento'],
    commonMistakes: ['No llegar a extensión completa'],
    tips: ['Imposible hacer trampa con el cuerpo', 'Excelente para aislar el bíceps'],
    variants: ['biceps-barbell-curl'],
  },
  {
    id: 'biceps-concentration-curl',
    name: 'Concentration Curl',
    nameEs: 'Curl Concentrado',
    muscleGroups: { primary: ['biceps'], secondary: [] },
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Sentado, codo apoyado en el muslo interno', 'Flexiona la mancuerna hacia el hombro', 'Aprieta al final', 'Baja controladamente'],
    commonMistakes: ['Mover el codo del muslo'],
    tips: ['Excelente para el pico del bíceps', 'Mira el músculo durante el movimiento'],
    variants: ['biceps-preacher-curl'],
  },
  {
    id: 'biceps-cable-curl',
    name: 'Cable Curl',
    nameEs: 'Curl en Cable',
    muscleGroups: { primary: ['biceps'], secondary: ['forearms'] },
    equipment: ['cable'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Cable en posición baja', 'Agarre supino', 'Flexiona hacia los hombros', 'Controla el regreso'],
    commonMistakes: ['Permitir que el cable tire rápido'],
    tips: ['Tensión constante en todo el rango', 'Ideal para el final del entrenamiento'],
    variants: ['biceps-barbell-curl'],
  },
  // ===== TRÍCEPS =====
  {
    id: 'triceps-close-grip-bench',
    name: 'Close Grip Bench Press',
    nameEs: 'Press de Banca Agarre Cerrado',
    muscleGroups: { primary: ['triceps'], secondary: ['chest', 'shoulders'] },
    equipment: ['barbell', 'bench'],
    movementPattern: 'push-horizontal',
    difficulty: 'intermediate',
    instructions: ['Agarre a la anchura de los hombros', 'Codos pegados al cuerpo', 'Baja al pecho', 'Empuja extendiendo los tríceps'],
    commonMistakes: ['Agarre demasiado estrecho (lesiona muñecas)', 'Codos muy abiertos'],
    tips: ['La anchura de hombros es suficiente', 'Excelente para masa de tríceps'],
    variants: ['triceps-french-press', 'chest-barbell-bench-press'],
  },
  {
    id: 'triceps-french-press',
    name: 'Skull Crusher / French Press',
    nameEs: 'Press Francés',
    muscleGroups: { primary: ['triceps'], secondary: [] },
    equipment: ['barbell', 'ez-bar', 'dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'intermediate',
    instructions: ['Acuéstate con barra sobre el pecho', 'Brazos extendidos hacia arriba', 'Dobla solo los codos bajando la barra hacia la frente', 'Extiende los codos para subir'],
    commonMistakes: ['Mover los codos hacia adelante o atrás', 'Peso excesivo'],
    tips: ['Codos apuntando al techo en todo momento', 'Con EZ-bar hay menos tensión en muñecas'],
    variants: ['triceps-overhead-extension'],
  },
  {
    id: 'triceps-overhead-extension',
    name: 'Overhead Tricep Extension',
    nameEs: 'Extensión de Tríceps sobre la Cabeza',
    muscleGroups: { primary: ['triceps'], secondary: [] },
    equipment: ['dumbbell', 'cable'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['De pie o sentado, mancuerna sobre la cabeza con ambas manos', 'Codos apuntando hacia arriba', 'Baja la mancuerna detrás de la cabeza', 'Extiende los codos'],
    commonMistakes: ['Mover los codos hacia afuera'],
    tips: ['Trabaja la cabeza larga del tríceps (la más grande)', 'Excelente rango de movimiento'],
    variants: ['triceps-french-press'],
  },
  {
    id: 'triceps-cable-pushdown',
    name: 'Cable Pushdown',
    nameEs: 'Extensión de Tríceps en Polea Alta',
    muscleGroups: { primary: ['triceps'], secondary: [] },
    equipment: ['cable'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Cable en posición alta', 'Codos fijos al cuerpo', 'Empuja hacia abajo extendiendo los codos', 'Controla el regreso'],
    commonMistakes: ['Mover los codos', 'Inclinarse demasiado'],
    tips: ['Prueba con barra recta, cuerda o V-bar', 'La cuerda permite supinar al final para más contracción'],
    variants: ['triceps-cable-overhead', 'triceps-kickback'],
  },
  {
    id: 'triceps-cable-overhead',
    name: 'Cable Overhead Extension',
    nameEs: 'Extensión de Tríceps en Polea Alta (Sobre cabeza)',
    muscleGroups: { primary: ['triceps'], secondary: [] },
    equipment: ['cable'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Cable en posición alta, de espaldas a la máquina', 'Inclínate ligeramente hacia adelante', 'Extiende los tríceps hacia adelante', 'Controla el regreso'],
    commonMistakes: ['Mover los codos'],
    tips: ['Trabaja la cabeza larga con tensión constante'],
    variants: ['triceps-cable-pushdown', 'triceps-overhead-extension'],
  },
  {
    id: 'triceps-kickback',
    name: 'Tricep Kickback',
    nameEs: 'Extensión de Tríceps en Patada',
    muscleGroups: { primary: ['triceps'], secondary: [] },
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Inclinado hacia adelante, codo a 90°', 'Extiende el antebrazo hacia atrás', 'Aprieta el tríceps al final', 'Regresa controladamente'],
    commonMistakes: ['Bajar el codo al extender'],
    tips: ['Peso ligero, tensión en todo el rango', 'El codo debe quedar alto y quieto'],
    variants: ['triceps-cable-pushdown'],
  },
  {
    id: 'triceps-dips',
    name: 'Tricep Dips',
    nameEs: 'Fondos de Tríceps',
    muscleGroups: { primary: ['triceps'], secondary: ['shoulders', 'chest'] },
    equipment: ['bodyweight', 'bench'],
    movementPattern: 'push-vertical',
    difficulty: 'beginner',
    instructions: ['Manos en el borde de un banco, cuerpo vertical', 'Baja doblando los codos hasta 90°', 'Empuja hacia arriba'],
    commonMistakes: ['Inclinarse hacia adelante (activa el pecho)'],
    tips: ['Mantén el cuerpo vertical para aislar el tríceps', 'Añade peso en el regazo para progresar'],
    variants: ['chest-dips', 'triceps-close-grip-bench'],
  },
  // ===== CUÁDRICEPS =====
  {
    id: 'quads-squat',
    name: 'Barbell Back Squat',
    nameEs: 'Sentadilla con Barra',
    muscleGroups: { primary: ['quadriceps'], secondary: ['glutes', 'hamstrings', 'core'] },
    equipment: ['barbell'],
    movementPattern: 'squat',
    difficulty: 'advanced',
    instructions: ['Barra sobre los trapecios (high bar) o parte superior de la espalda (low bar)', 'Pies a la anchura de hombros, puntas ligeramente afuera', 'Baja como si fueras a sentarte', 'Muslos paralelos al suelo o por debajo', 'Empuja el suelo para subir'],
    commonMistakes: ['Rodillas colapsando hacia adentro', 'Talones levantándose', 'Torso inclinado excesivamente'],
    tips: ['Mantén el peso en los talones y metatarsos', '"Empuja las rodillas hacia afuera" durante todo el movimiento'],
    variants: ['quads-goblet-squat', 'quads-leg-press', 'quads-front-squat'],
  },
  {
    id: 'quads-front-squat',
    name: 'Front Squat',
    nameEs: 'Sentadilla Frontal',
    muscleGroups: { primary: ['quadriceps'], secondary: ['glutes', 'core', 'back'] },
    equipment: ['barbell'],
    movementPattern: 'squat',
    difficulty: 'advanced',
    instructions: ['Barra en la parte frontal de los hombros', 'Codos arriba, paralelos al suelo', 'Baja manteniendo el torso vertical', 'Empuja hacia arriba'],
    commonMistakes: ['Codos caen y se suelta la barra', 'Torso no vertical'],
    tips: ['Mayor activación de cuádriceps que la sentadilla trasera', 'Requiere buena movilidad de tobillo y hombro'],
    variants: ['quads-squat'],
  },
  {
    id: 'quads-goblet-squat',
    name: 'Goblet Squat',
    nameEs: 'Sentadilla Goblet',
    muscleGroups: { primary: ['quadriceps'], secondary: ['glutes', 'core'] },
    equipment: ['dumbbell', 'kettlebell'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    instructions: ['Sostén la pesa frente al pecho', 'Pies a la anchura de hombros', 'Baja profundo manteniendo el torso erguido', 'Empuja hacia arriba'],
    commonMistakes: ['No bajar suficientemente profundo'],
    tips: ['Excelente para aprender la mecánica de la sentadilla', 'Favorece el torso vertical'],
    variants: ['quads-squat'],
  },
  {
    id: 'quads-leg-press',
    name: 'Leg Press',
    nameEs: 'Prensa de Piernas',
    muscleGroups: { primary: ['quadriceps'], secondary: ['glutes', 'hamstrings'] },
    equipment: ['machine'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    instructions: ['Pies a la anchura de caderas o más', 'Baja hasta 90° o más profundo', 'Empuja hasta casi extender (no bloquear)', 'Controla la bajada'],
    commonMistakes: ['Bloquear las rodillas arriba', 'Talones levantándose'],
    tips: ['Pies altos activan más isquios/glúteos', 'Pies bajos activan más cuádriceps'],
    variants: ['quads-squat', 'quads-hack-squat'],
  },
  {
    id: 'quads-hack-squat',
    name: 'Hack Squat',
    nameEs: 'Sentadilla Hack',
    muscleGroups: { primary: ['quadriceps'], secondary: ['glutes'] },
    equipment: ['machine'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    instructions: ['Espalda apoyada en el asiento inclinado', 'Pies en la plataforma', 'Baja controladamente', 'Empuja hasta casi extender'],
    commonMistakes: ['Talones levantados', 'Rodillas hacia adentro'],
    tips: ['Pies bajos en la plataforma = más cuádriceps'],
    variants: ['quads-leg-press', 'quads-squat'],
  },
  {
    id: 'quads-leg-extension',
    name: 'Leg Extension',
    nameEs: 'Extensión de Piernas',
    muscleGroups: { primary: ['quadriceps'], secondary: [] },
    equipment: ['machine'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Siéntate y ajusta el rodillo sobre los tobillos', 'Extiende las piernas hasta arriba', 'Aprieta los cuádriceps', 'Baja controladamente'],
    commonMistakes: ['Usar impulso', 'No llegar a extensión completa'],
    tips: ['Excelente finalizador para cuádriceps', 'Activa el VMO (muslo interno)'],
    variants: ['quads-leg-press'],
  },
  {
    id: 'quads-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    nameEs: 'Sentadilla Búlgara',
    muscleGroups: { primary: ['quadriceps', 'glutes'], secondary: ['hamstrings', 'core'] },
    equipment: ['dumbbell', 'barbell'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    instructions: ['Pie trasero elevado en banco', 'Baja la rodilla trasera hacia el suelo', 'Mantén el torso erguido', 'Empuja con el pie delantero'],
    commonMistakes: ['Pie delantero demasiado cerca del banco', 'Torso excesivamente inclinado'],
    tips: ['Unilateral = detecta y corrige desequilibrios', 'Más estiramiento del flexor de cadera que la sentadilla'],
    variants: ['quads-squat', 'glutes-hip-thrust'],
  },
  {
    id: 'quads-walking-lunges',
    name: 'Walking Lunges',
    nameEs: 'Zancadas Caminando',
    muscleGroups: { primary: ['quadriceps', 'glutes'], secondary: ['hamstrings', 'core'] },
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    instructions: ['Da un paso largo hacia adelante', 'Baja la rodilla trasera casi al suelo', 'Empuja para llevar el pie trasero hacia adelante', 'Repite con el otro lado'],
    commonMistakes: ['Rodilla delantera sobrepasando la punta del pie'],
    tips: ['Mantén el torso erguido', 'Pasos largos = más glúteos, pasos cortos = más cuádriceps'],
    variants: ['quads-bulgarian-split-squat'],
  },
  // ===== ISQUIOTIBIALES =====
  {
    id: 'hamstrings-leg-curl',
    name: 'Lying Leg Curl',
    nameEs: 'Curl Femoral Acostado',
    muscleGroups: { primary: ['hamstrings'], secondary: [] },
    equipment: ['machine'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Acuéstate en la máquina, rodillo sobre los talones', 'Flexiona las piernas hacia los glúteos', 'Aprieta los isquios', 'Baja lentamente'],
    commonMistakes: ['Levantar las caderas', 'No llegar a rango completo'],
    tips: ['Punta de pies en flexión (dorsiflexión) activa más los isquios'],
    variants: ['back-romanian-deadlift'],
  },
  {
    id: 'hamstrings-seated-leg-curl',
    name: 'Seated Leg Curl',
    nameEs: 'Curl Femoral Sentado',
    muscleGroups: { primary: ['hamstrings'], secondary: [] },
    equipment: ['machine'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Ajusta el asiento para que las rodillas queden en el eje de la máquina', 'Flexiona hasta que los isquios estén completamente contraídos', 'Controla el regreso'],
    commonMistakes: ['No ajustar correctamente el asiento'],
    tips: ['El estiramiento en la posición inicial es mayor que en el acostado'],
    variants: ['hamstrings-leg-curl', 'back-romanian-deadlift'],
  },
  {
    id: 'hamstrings-nordic-curl',
    name: 'Nordic Curl',
    nameEs: 'Curl Nórdico',
    muscleGroups: { primary: ['hamstrings'], secondary: ['glutes'] },
    equipment: ['bodyweight'],
    movementPattern: 'hinge',
    difficulty: 'advanced',
    instructions: ['Arrodillado con pies fijos', 'Baja el torso hacia el suelo controladamente con los isquios', 'Usa las manos para amortiguar', 'Sube empujando con los isquios'],
    commonMistakes: ['Bajar demasiado rápido'],
    tips: ['Uno de los mejores ejercicios para fortalecer y prevenir lesiones de isquios'],
    variants: ['hamstrings-leg-curl'],
  },
  // ===== GLÚTEOS =====
  {
    id: 'glutes-hip-thrust',
    name: 'Hip Thrust',
    nameEs: 'Hip Thrust / Empuje de Cadera',
    muscleGroups: { primary: ['glutes'], secondary: ['hamstrings', 'quadriceps'] },
    equipment: ['barbell', 'bench'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    instructions: ['Espalda alta apoyada en el banco', 'Barra en el pliegue de la cadera', 'Empuja las caderas hacia arriba', 'Aprieta los glúteos al final', 'Baja controladamente'],
    commonMistakes: ['No llevar las caderas a la extensión completa', 'La espalda deslizarse hacia abajo'],
    tips: ['El mejor ejercicio para aislar los glúteos', 'Pies a la anchura de caderas'],
    variants: ['glutes-glute-bridge', 'back-romanian-deadlift'],
  },
  {
    id: 'glutes-glute-bridge',
    name: 'Glute Bridge',
    nameEs: 'Puente de Glúteos',
    muscleGroups: { primary: ['glutes'], secondary: ['hamstrings'] },
    equipment: ['bodyweight', 'dumbbell'],
    movementPattern: 'hinge',
    difficulty: 'beginner',
    instructions: ['Acuéstate con rodillas dobladas', 'Empuja las caderas hacia arriba', 'Aprieta glúteos al final', 'Baja lentamente'],
    commonMistakes: ['No extender completamente la cadera'],
    tips: ['Versión más accesible del hip thrust', 'Bueno para principiantes y calentamiento'],
    variants: ['glutes-hip-thrust'],
  },
  {
    id: 'glutes-cable-kickback',
    name: 'Cable Glute Kickback',
    nameEs: 'Patada Trasera en Cable',
    muscleGroups: { primary: ['glutes'], secondary: ['hamstrings'] },
    equipment: ['cable'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Tobillo en el accesorio del cable bajo', 'Inclínate ligeramente', 'Lleva la pierna hacia atrás extendiendo la cadera', 'Aprieta el glúteo', 'Regresa controladamente'],
    commonMistakes: ['Usar la espalda baja para extender'],
    tips: ['Mantén la rodilla ligeramente flexionada'],
    variants: ['glutes-hip-thrust'],
  },
  {
    id: 'glutes-abductor-machine',
    name: 'Hip Abductor Machine',
    nameEs: 'Abductor en Máquina',
    muscleGroups: { primary: ['glutes'], secondary: [] },
    equipment: ['machine'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Siéntate con las piernas dentro de los rodillos', 'Abre las piernas contra la resistencia', 'Aprieta los glúteos al final', 'Cierra controladamente'],
    commonMistakes: ['Usar el torso para ayudar'],
    tips: ['Activa el glúteo medio (clave para la estabilidad de la cadera)'],
    variants: ['glutes-hip-thrust'],
  },
  // ===== PANTORRILLAS =====
  {
    id: 'calves-standing-calf-raise',
    name: 'Standing Calf Raise',
    nameEs: 'Elevación de Pantorrillas de Pie',
    muscleGroups: { primary: ['calves'], secondary: [] },
    equipment: ['machine', 'bodyweight'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Metatarsos en el borde de la plataforma', 'Baja hasta el estiramiento máximo', 'Sube hasta la punta de pie máxima', 'Pausa arriba'],
    commonMistakes: ['No bajar suficientemente', 'Rebotar en la parte inferior'],
    tips: ['Rango de movimiento completo es esencial', 'Los gemelos responden bien al volumen alto'],
    variants: ['calves-seated-calf-raise'],
  },
  {
    id: 'calves-seated-calf-raise',
    name: 'Seated Calf Raise',
    nameEs: 'Elevación de Pantorrillas Sentado',
    muscleGroups: { primary: ['calves'], secondary: [] },
    equipment: ['machine'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Siéntate con metatarsos en la plataforma', 'Rodillos sobre los muslos', 'Baja hasta el estiramiento', 'Sube a la punta máxima'],
    commonMistakes: ['No llegar al rango completo'],
    tips: ['Activa más el soleo (músculo profundo) que los gemelos', 'La variación sentada es clave para pantorrillas completas'],
    variants: ['calves-standing-calf-raise'],
  },
  // ===== CORE =====
  {
    id: 'core-plank',
    name: 'Plank',
    nameEs: 'Plancha',
    muscleGroups: { primary: ['core'], secondary: ['shoulders', 'glutes'] },
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'beginner',
    instructions: ['Apóyate en los antebrazos y puntas de pie', 'Cuerpo recto de cabeza a talones', 'Mantén la posición', 'Respira normalmente'],
    commonMistakes: ['Cadera hacia arriba o abajo', 'Aguantar la respiración'],
    tips: ['Aprieta glúteos y abdomen simultáneamente', 'La posición correcta es más importante que la duración'],
    variants: ['core-side-plank', 'core-ab-wheel'],
  },
  {
    id: 'core-side-plank',
    name: 'Side Plank',
    nameEs: 'Plancha Lateral',
    muscleGroups: { primary: ['core'], secondary: ['shoulders', 'glutes'] },
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'beginner',
    instructions: ['Apóyate en un antebrazo lateral y borde del pie', 'Cuerpo recto de lado', 'Mantén la cadera levantada', 'Respira normalmente'],
    commonMistakes: ['Cadera cayendo', 'No mantener el cuerpo alineado'],
    tips: ['Trabaja el core lateral y el cuadrado lumbar'],
    variants: ['core-plank'],
  },
  {
    id: 'core-crunch',
    name: 'Crunch',
    nameEs: 'Crunch Abdominal',
    muscleGroups: { primary: ['core'], secondary: [] },
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'beginner',
    instructions: ['Acuéstate boca arriba, rodillas dobladas', 'Manos detrás de la cabeza o en el pecho', 'Flexiona la columna levantando los hombros', 'Aprieta y baja controladamente'],
    commonMistakes: ['Tirar del cuello con las manos', 'Usar el impulso para subir'],
    tips: ['El movimiento es pequeño: solo los hombros se separan del suelo'],
    variants: ['core-plank', 'core-hanging-leg-raise'],
  },
  {
    id: 'core-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    nameEs: 'Elevación de Piernas Colgado',
    muscleGroups: { primary: ['core'], secondary: ['lats', 'forearms'] },
    equipment: ['pull-up-bar'],
    movementPattern: 'core',
    difficulty: 'intermediate',
    instructions: ['Cuélgate de la barra con brazos extendidos', 'Levanta las piernas hasta paralelas al suelo o más', 'Baja controladamente sin inercia'],
    commonMistakes: ['Usar inercia', 'No controlar la bajada'],
    tips: ['Mantén las piernas rectas para mayor dificultad', 'La versión con rodillas dobladas es más fácil'],
    variants: ['core-ab-wheel', 'core-crunch'],
  },
  {
    id: 'core-ab-wheel',
    name: 'Ab Wheel Rollout',
    nameEs: 'Rueda Abdominal',
    muscleGroups: { primary: ['core'], secondary: ['lats', 'shoulders'] },
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'advanced',
    instructions: ['Arrodillado con la rueda en el suelo', 'Rueda hacia adelante manteniendo el core tenso', 'Llega tan lejos como puedas sin que la espalda se hunda', 'Regresa usando el core'],
    commonMistakes: ['Hundir la espalda al extender'],
    tips: ['Uno de los mejores ejercicios para el core', 'Empieza con rangos cortos'],
    variants: ['core-plank'],
  },
  {
    id: 'core-dragon-flag',
    name: 'Dragon Flag',
    nameEs: 'Bandera del Dragón',
    muscleGroups: { primary: ['core'], secondary: ['lats', 'glutes'] },
    equipment: ['bench'],
    movementPattern: 'core',
    difficulty: 'advanced',
    instructions: ['Acuéstate en el banco, agarra el borde detrás de la cabeza', 'Levanta el cuerpo hasta la vertical', 'Baja controladamente manteniendo el cuerpo recto', 'Para antes de tocar el banco'],
    commonMistakes: ['Doblar la cadera al bajar'],
    tips: ['Requiere un core muy fuerte', 'Progresión: empieza con legs raises y planches'],
    variants: ['core-hanging-leg-raise', 'core-ab-wheel'],
  },
  // ===== TRAPECIOS =====
  {
    id: 'traps-barbell-shrug',
    name: 'Barbell Shrug',
    nameEs: 'Encogimiento con Barra',
    muscleGroups: { primary: ['traps'], secondary: ['forearms'] },
    equipment: ['barbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Agarra la barra con agarre prono', 'Sube los hombros hacia las orejas', 'Pausa arriba', 'Baja controladamente'],
    commonMistakes: ['Rotar los hombros', 'No llegar al tope'],
    tips: ['Evita el movimiento circular de los hombros', 'La pausa arriba maximiza la contracción'],
    variants: ['traps-dumbbell-shrug'],
  },
  {
    id: 'traps-dumbbell-shrug',
    name: 'Dumbbell Shrug',
    nameEs: 'Encogimiento con Mancuernas',
    muscleGroups: { primary: ['traps'], secondary: ['forearms'] },
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Mancuernas a los lados', 'Sube los hombros hacia las orejas', 'Pausa', 'Baja lentamente'],
    commonMistakes: ['Rotar los hombros'],
    tips: ['Mayor rango de movimiento que con barra'],
    variants: ['traps-barbell-shrug'],
  },
  // ===== DORSALES EXTRA =====
  {
    id: 'lats-pullover',
    name: 'Dumbbell Pullover',
    nameEs: 'Pullover con Mancuerna',
    muscleGroups: { primary: ['lats'], secondary: ['chest', 'triceps'] },
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'pull-vertical',
    difficulty: 'intermediate',
    instructions: ['Acuéstate perpendicular al banco', 'Sostén la mancuerna sobre el pecho con ambas manos', 'Lleva la mancuerna hacia atrás sobre la cabeza en arco', 'Regresa al punto inicial'],
    commonMistakes: ['Doblar demasiado los codos'],
    tips: ['Trabaja tanto el dorsal como el pecho', 'Mantén los codos ligeramente doblados'],
    variants: ['back-lat-pulldown', 'back-pull-up'],
  },
  {
    id: 'lats-straight-arm-pulldown',
    name: 'Straight Arm Pulldown',
    nameEs: 'Jalón con Brazos Rectos',
    muscleGroups: { primary: ['lats'], secondary: ['chest'] },
    equipment: ['cable'],
    movementPattern: 'pull-vertical',
    difficulty: 'beginner',
    instructions: ['Cable en posición alta', 'Inclínate ligeramente hacia adelante', 'Brazos casi rectos, solo ligera flexión en codos', 'Lleva los brazos hacia abajo hasta las caderas'],
    commonMistakes: ['Doblar demasiado los codos (convierte en jalón)'],
    tips: ['Excelente para sentir y aislar el dorsal', 'Ideal para aprender a activar los dorsales'],
    variants: ['back-lat-pulldown'],
  },
  // ===== ANTEBRAZOS =====
  {
    id: 'forearms-wrist-curl',
    name: 'Wrist Curl',
    nameEs: 'Curl de Muñeca',
    muscleGroups: { primary: ['forearms'], secondary: [] },
    equipment: ['barbell', 'dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Antebrazos apoyados en un banco, muñecas hacia afuera', 'Baja la barra permitiendo que la muñeca se extienda', 'Flexiona la muñeca hacia arriba', 'Baja controladamente'],
    commonMistakes: ['Rango de movimiento insuficiente'],
    tips: ['Trabaja los flexores del antebrazo', 'Alta repetición funciona bien aquí'],
    variants: ['forearms-reverse-curl'],
  },
  {
    id: 'forearms-reverse-curl',
    name: 'Reverse Curl',
    nameEs: 'Curl Inverso',
    muscleGroups: { primary: ['forearms'], secondary: ['biceps'] },
    equipment: ['barbell', 'ez-bar', 'dumbbell'],
    movementPattern: 'isolation',
    difficulty: 'beginner',
    instructions: ['Agarre prono', 'Flexiona los codos hasta arriba', 'Baja controladamente'],
    commonMistakes: ['Mover los codos'],
    tips: ['Trabaja los extensores del antebrazo y braquiorradial'],
    variants: ['forearms-wrist-curl', 'biceps-hammer-curl'],
  },
]

export function getSeedExercises(): Exercise[] {
  return EXERCISES_DATA.map(data => Exercise.fromJSON(data))
}
